import enum
class ModuleTag(enum.IntEnum):
   """
   Tags which categorize a module within Rack.
   """
   
   '''[[[cog
   tags = ['NO_TAG', 'AMPLIFIER_TAG', 'ARPEGGIATOR_TAG', 'ATTENUATOR_TAG',
   'BLANK_TAG', 'CHORUS_TAG', 'CLOCK_MODULATOR_TAG', 'CLOCK_TAG',
   'COMPRESSOR_TAG', 'CONTROLLER_TAG', 'DELAY_TAG', 'DIGITAL_TAG',
   'DISTORTION_TAG', 'DRUM_TAG', 'DUAL_TAG', 'DYNAMICS_TAG',
   'EFFECT_TAG', 'ENVELOPE_FOLLOWER_TAG', 'ENVELOPE_GENERATOR_TAG',
   'EQUALIZER_TAG', 'EXTERNAL_TAG', 'FILTER_TAG', 'FLANGER_TAG',
   'FUNCTION_GENERATOR_TAG', 'GRANULAR_TAG', 'LFO_TAG', 'LIMITER_TAG',
   'LOGIC_TAG', 'LOW_PASS_GATE_TAG', 'MIDI_TAG', 'MIXER_TAG',
   'MULTIPLE_TAG', 'NOISE_TAG', 'OSCILLATOR_TAG', 'PANNING_TAG',
   'PHASER_TAG', 'PHYSICAL_MODELING_TAG', 'QUAD_TAG', 'QUANTIZER_TAG',
   'RANDOM_TAG', 'RECORDING_TAG', 'REVERB_TAG', 'RING_MODULATOR_TAG',
   'SAMPLE_AND_HOLD_TAG', 'SAMPLER_TAG', 'SEQUENCER_TAG', 'SLEW_LIMITER_TAG',
   'SWITCH_TAG', 'SYNTH_VOICE_TAG', 'TUNER_TAG', 'UTILITY_TAG', 'VISUAL_TAG',
   'VOCODER_TAG', 'WAVESHAPER_TAG', 'NUM_TAGS']
   for i, t in enumerate(tags):
      cog.outl('{} = {}'.format(t, i))
   ]]]'''
   NO_TAG = 0
   AMPLIFIER_TAG = 1
   ARPEGGIATOR_TAG = 2
   ATTENUATOR_TAG = 3
   BLANK_TAG = 4
   CHORUS_TAG = 5
   CLOCK_MODULATOR_TAG = 6
   CLOCK_TAG = 7
   COMPRESSOR_TAG = 8
   CONTROLLER_TAG = 9
   DELAY_TAG = 10
   DIGITAL_TAG = 11
   DISTORTION_TAG = 12
   DRUM_TAG = 13
   DUAL_TAG = 14
   DYNAMICS_TAG = 15
   EFFECT_TAG = 16
   ENVELOPE_FOLLOWER_TAG = 17
   ENVELOPE_GENERATOR_TAG = 18
   EQUALIZER_TAG = 19
   EXTERNAL_TAG = 20
   FILTER_TAG = 21
   FLANGER_TAG = 22
   FUNCTION_GENERATOR_TAG = 23
   GRANULAR_TAG = 24
   LFO_TAG = 25
   LIMITER_TAG = 26
   LOGIC_TAG = 27
   LOW_PASS_GATE_TAG = 28
   MIDI_TAG = 29
   MIXER_TAG = 30
   MULTIPLE_TAG = 31
   NOISE_TAG = 32
   OSCILLATOR_TAG = 33
   PANNING_TAG = 34
   PHASER_TAG = 35
   PHYSICAL_MODELING_TAG = 36
   QUAD_TAG = 37
   QUANTIZER_TAG = 38
   RANDOM_TAG = 39
   RECORDING_TAG = 40
   REVERB_TAG = 41
   RING_MODULATOR_TAG = 42
   SAMPLE_AND_HOLD_TAG = 43
   SAMPLER_TAG = 44
   SEQUENCER_TAG = 45
   SLEW_LIMITER_TAG = 46
   SWITCH_TAG = 47
   SYNTH_VOICE_TAG = 48
   TUNER_TAG = 49
   UTILITY_TAG = 50
   VISUAL_TAG = 51
   VOCODER_TAG = 52
   WAVESHAPER_TAG = 53
   NUM_TAGS = 54
   #[[[end]]]
